import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request';


const graphcms = new GraphQLClient(
  'https://api-us-east-1.graphcms.com/v2/cl54ih7ps394v01ug1os0a3q6/master'
  );

  const QUERY = gql`
    {
      posts {
        id,
        title,
        datePublished,
        slug,
        content {
          html
        }
        author {
          name,
          avatar {
            url
          }
        }
        coverPhoto{
          publishedAt {
            createdBy {
              id
            }
            url
          }
        }
      }
    }
  `

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Spencers Dev Journal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
      </main>

    </div>
  )
}
